/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tensorflow_demo_MobileNetSSD */

#ifndef _Included_com_chaoying_ncnn_MobileNetSSD
#define _Included_com_chaoying_ncnn_MobileNetSSD
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chaoying_ncnn_MobileNetSSD
 * Method:    Init
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_chaoying_ncnn_MobileNetSSD_Init
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_chaoying_ncnn_MobileNetSSD
 * Method:    Detect
 * Signature: (Ljava/lang/Object;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_chaoying_ncnn_MobileNetSSD_Detect
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
